export const REVIEWS = [
  {
    name: "Jan van der Berg",
    location: "Amsterdam",
    rating: 5,
    date: "2 weken geleden",
    text: "Riool verstopt op zondagavond, binnen een uur was de monteur er. Snel opgelost en alles netjes achtergelaten. Top service!",
  },
  {
    name: "Maria Jansen",
    location: "Rotterdam",
    rating: 5,
    date: "1 maand geleden",
    text: "Professioneel en vriendelijk. Afvoer was compleet verstopt, maar binnen een half uur stroomde alles weer. Eerlijke prijs ook.",
  },
  {
    name: "Peter de Vries",
    location: "Utrecht",
    rating: 5,
    date: "3 weken geleden",
    text: "Camera-inspectie laten doen vanwege terugkerende verstoppingen. Wortelgroei gevonden en direct aangepakt. Zeer tevreden!",
  },
  {
    name: "Sophie Bakker",
    location: "Den Haag",
    rating: 5,
    date: "2 maanden geleden",
    text: "WC verstopt en de loodgieter was er binnen 2 uur. Netjes en hygiënisch gewerkt. Prijs was precies zoals afgesproken.",
  },
  {
    name: "Henk Vermeulen",
    location: "Eindhoven",
    rating: 5,
    date: "1 week geleden",
    text: "Rioolreiniging voor ons bedrijfspand. Vakkundig uitgevoerd met hogedrukreiniging. Merken direct verschil. Aanrader!",
  },
  {
    name: "Linda Smit",
    location: "Groningen",
    rating: 5,
    date: "3 weken geleden",
    text: "Keukenafvoer zat helemaal dicht door vet. Monteur had het in 20 minuten opgelost. Gaf ook goede tips om het te voorkomen.",
  },
  {
    name: "Tom Willems",
    location: "Breda",
    rating: 5,
    date: "1 maand geleden",
    text: "Zeer vakkundig en betrouwbaar. Rioolreparatie uitgevoerd zonder de hele tuin open te breken. Knap werk!",
  },
  {
    name: "Emma de Jong",
    location: "Nijmegen",
    rating: 5,
    date: "2 weken geleden",
    text: "Wateroverlast in de kelder door verstopte hemelwaterafvoer. Snel geholpen en het probleem is definitief opgelost.",
  },
  {
    name: "Robert Mulder",
    location: "Tilburg",
    rating: 5,
    date: "4 weken geleden",
    text: "Al twee keer gebruik gemaakt van Loodgieter. Altijd op tijd, altijd eerlijk en altijd goed werk. Vaste klant!",
  },
  {
    name: "Annemarie Visser",
    location: "Almere",
    rating: 5,
    date: "1 week geleden",
    text: "Spoedgeval op zaterdag en toch snel geholpen. De monteur was vriendelijk en professioneel. Zeker een aanrader!",
  },
];
